[package]
name = "ringu"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
description= "no_std ring buffer"
edition = "2018"


[dependencies]


[dev-dependencies]
lazy_static = "1.4.0"